import * as Types from '../types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CommentFieldsFragment = { __typename?: 'Comment', id: string, comment: string, createdAt: string };

export type BasicPostFieldsFragment = { __typename?: 'Post', id: string, text?: string | null | undefined, image?: string | null | undefined, createdAt: string };

export type LikesInfoFragment = { __typename?: 'Post', likesCount: number, latestLike?: string | null | undefined, likedByAuthUser?: boolean | null | undefined };

export type CommentsInfoFragment = { __typename?: 'Post', commentsCount: number, latestComment?: { __typename?: 'Comment', id: string, comment: string, createdAt: string, author: { __typename?: 'User', id: string, fullName: string, username: string, image?: string | null | undefined } } | null | undefined };

export type PostFieldsFragment = { __typename?: 'Post', id: string, text?: string | null | undefined, image?: string | null | undefined, createdAt: string, commentsCount: number, likesCount: number, latestLike?: string | null | undefined, likedByAuthUser?: boolean | null | undefined, author: { __typename?: 'User', id: string, fullName: string, username: string, image?: string | null | undefined }, latestComment?: { __typename?: 'Comment', id: string, comment: string, createdAt: string, author: { __typename?: 'User', id: string, fullName: string, username: string, image?: string | null | undefined } } | null | undefined };

export type UploadFileMutationVariables = Types.Exact<{
  file: Types.Scalars['Upload'];
}>;


export type UploadFileMutation = { __typename?: 'Mutation', uploadFile?: { __typename?: 'File', url?: string | null | undefined, filename?: string | null | undefined, mimetype?: string | null | undefined, encoding?: string | null | undefined } | null | undefined };

export type CreatePostMutationVariables = Types.Exact<{
  text?: Types.Maybe<Types.Scalars['String']>;
  image?: Types.Maybe<Types.Scalars['String']>;
}>;


export type CreatePostMutation = { __typename?: 'Mutation', post?: { __typename?: 'Post', id: string, text?: string | null | undefined, image?: string | null | undefined, createdAt: string, author: { __typename?: 'User', postsCount: number, id: string, fullName: string, username: string, image?: string | null | undefined } } | null | undefined };

export type RemovePostMutationVariables = Types.Exact<{
  id: Types.Scalars['ID'];
}>;


export type RemovePostMutation = { __typename?: 'Mutation', removePost?: string | null | undefined };

export type BasicUserFieldsFragment = { __typename?: 'User', id: string, fullName: string, username: string, image?: string | null | undefined };

export type UserFieldsFragment = { __typename?: 'User', email: string, bio?: string | null | undefined, coverImage?: string | null | undefined, postsCount: number, createdAt: string, id: string, fullName: string, username: string, image?: string | null | undefined };

export type SetUserPhotoMutationVariables = Types.Exact<{
  file: Types.Scalars['Upload'];
}>;


export type SetUserPhotoMutation = { __typename?: 'Mutation', setUserPhoto?: { __typename?: 'User', email: string, bio?: string | null | undefined, coverImage?: string | null | undefined, postsCount: number, createdAt: string, id: string, fullName: string, username: string, image?: string | null | undefined } | null | undefined };

export type SetUserCoverMutationVariables = Types.Exact<{
  file: Types.Scalars['Upload'];
}>;


export type SetUserCoverMutation = { __typename?: 'Mutation', setUserCover?: { __typename?: 'User', email: string, bio?: string | null | undefined, coverImage?: string | null | undefined, postsCount: number, createdAt: string, id: string, fullName: string, username: string, image?: string | null | undefined } | null | undefined };

export type SetUserBioMutationVariables = Types.Exact<{
  bio: Types.Scalars['String'];
}>;


export type SetUserBioMutation = { __typename?: 'Mutation', setUserBio?: { __typename?: 'User', email: string, bio?: string | null | undefined, coverImage?: string | null | undefined, postsCount: number, createdAt: string, id: string, fullName: string, username: string, image?: string | null | undefined } | null | undefined };

export const BasicPostFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BasicPostFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Post"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"image"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]} as unknown as DocumentNode<BasicPostFieldsFragment, unknown>;
export const BasicUserFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BasicUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"image"}}]}}]} as unknown as DocumentNode<BasicUserFieldsFragment, unknown>;
export const CommentFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CommentFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Comment"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"comment"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]} as unknown as DocumentNode<CommentFieldsFragment, unknown>;
export const CommentsInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CommentsInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Post"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"latestComment"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CommentFields"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicUserFields"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"commentsCount"}}]}},...CommentFieldsFragmentDoc.definitions,...BasicUserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<CommentsInfoFragment, unknown>;
export const LikesInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"LikesInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Post"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"likesCount"}},{"kind":"Field","name":{"kind":"Name","value":"latestLike"}},{"kind":"Field","name":{"kind":"Name","value":"likedByAuthUser"}}]}}]} as unknown as DocumentNode<LikesInfoFragment, unknown>;
export const PostFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PostFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Post"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicPostFields"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicUserFields"}}]}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"CommentsInfo"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"LikesInfo"}}]}},...BasicPostFieldsFragmentDoc.definitions,...BasicUserFieldsFragmentDoc.definitions,...CommentsInfoFragmentDoc.definitions,...LikesInfoFragmentDoc.definitions]} as unknown as DocumentNode<PostFieldsFragment, unknown>;
export const UserFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"UserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicUserFields"}},{"kind":"Field","name":{"kind":"Name","value":"email"}},{"kind":"Field","name":{"kind":"Name","value":"bio"}},{"kind":"Field","name":{"kind":"Name","value":"coverImage"}},{"kind":"Field","name":{"kind":"Name","value":"postsCount"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}},...BasicUserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<UserFieldsFragment, unknown>;
export const UploadFileDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"uploadFile"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"file"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Upload"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uploadFile"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"file"},"value":{"kind":"Variable","name":{"kind":"Name","value":"file"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"filename"}},{"kind":"Field","name":{"kind":"Name","value":"mimetype"}},{"kind":"Field","name":{"kind":"Name","value":"encoding"}}]}}]}}]} as unknown as DocumentNode<UploadFileMutation, UploadFileMutationVariables>;
export const CreatePostDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"createPost"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"text"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"image"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"post"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"text"},"value":{"kind":"Variable","name":{"kind":"Name","value":"text"}}},{"kind":"Argument","name":{"kind":"Name","value":"image"},"value":{"kind":"Variable","name":{"kind":"Name","value":"image"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicPostFields"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasicUserFields"}},{"kind":"Field","name":{"kind":"Name","value":"postsCount"}}]}}]}}]}},...BasicPostFieldsFragmentDoc.definitions,...BasicUserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<CreatePostMutation, CreatePostMutationVariables>;
export const RemovePostDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"removePost"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"removePost"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}]}]}}]} as unknown as DocumentNode<RemovePostMutation, RemovePostMutationVariables>;
export const SetUserPhotoDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"setUserPhoto"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"file"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Upload"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"setUserPhoto"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"file"},"value":{"kind":"Variable","name":{"kind":"Name","value":"file"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserFields"}}]}}]}},...UserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<SetUserPhotoMutation, SetUserPhotoMutationVariables>;
export const SetUserCoverDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"setUserCover"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"file"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Upload"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"setUserCover"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"file"},"value":{"kind":"Variable","name":{"kind":"Name","value":"file"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserFields"}}]}}]}},...UserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<SetUserCoverMutation, SetUserCoverMutationVariables>;
export const SetUserBioDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"setUserBio"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"bio"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"setUserBio"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"bio"},"value":{"kind":"Variable","name":{"kind":"Name","value":"bio"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UserFields"}}]}}]}},...UserFieldsFragmentDoc.definitions]} as unknown as DocumentNode<SetUserBioMutation, SetUserBioMutationVariables>;